//*****************************************************************************
//
// Title:       SynergyMethodsPoolWrapper.cs
//
// Description: Pooling method wrappers for interface SynergyMethods
//
//*****************************************************************************
// WARNING: GENERATED CODE!
// This file was generated by CodeGen. Avoid editing the file if possible.
// Any changes you make will be lost of the file is re-generated.
//*****************************************************************************

using System.Collections;
using Microsoft.Extensions.ObjectPool;


namespace SynergyClient
{
	public static class SynergyMethodsPoolWrapper
	{
		public static void CopyFile(this ObjectPool<SynergyMethods> pool, string fromFile, string toFile, ref int ok, ref string errorMessage)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.CopyFile(fromFile,toFile,out ok,out errorMessage);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static int GetAddressForUpdate(this ObjectPool<SynergyMethods> pool, int CustomerID, int AddressID, ref Address Address, ref byte[] GRFA, ref string Message)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetAddressForUpdate(CustomerID,AddressID,out Address,out GRFA,out Message);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static void GetAllCustomers(this ObjectPool<SynergyMethods> pool, ref ArrayList Customers)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetAllCustomers(out Customers);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static int GetContactForUpdate(this ObjectPool<SynergyMethods> pool, int CustomerID, int ContactID, ref Contact Contact, ref byte[] GRFA, ref string Message)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetContactForUpdate(CustomerID,ContactID,out Contact,out GRFA,out Message);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static void GetCustomerAddresses(this ObjectPool<SynergyMethods> pool, int CustomerID, ref ArrayList Addresses)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetCustomerAddresses(CustomerID,out Addresses);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static void GetCustomerContacts(this ObjectPool<SynergyMethods> pool, int CustomerID, ref ArrayList Contacts)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetCustomerContacts(CustomerID,out Contacts);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static int GetCustomerForUpdate(this ObjectPool<SynergyMethods> pool, int CustomerID, ref Customer Customer, ref byte[] GRFA, ref string Message)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.GetCustomerForUpdate(CustomerID,out Customer,out GRFA,out Message);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static int UpdateContact(this ObjectPool<SynergyMethods> pool, ref Contact Contact, ref byte[] GRFA, ref string Message)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.UpdateContact(ref Contact,ref GRFA,out Message);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

		public static int UpdateCustomer(this ObjectPool<SynergyMethods> pool, ref Customer Customer, ref byte[] GRFA, ref string Message)
		{
			var clientInstance = pool.Get();
			try
			{
				return clientInstance.UpdateCustomer(ref Customer,ref GRFA,out Message);
			}
			finally
			{
				pool.Return(clientInstance);
			}
		}

	}
}
